-- Schema kept portable between PostgreSQL and H2 (PostgreSQL mode, used in tests).

CREATE TABLE virtual_keys (
    token_hash   VARCHAR(64) PRIMARY KEY,
    key_alias    VARCHAR(255),
    models       TEXT,                          -- comma-separated whitelist; NULL/empty = all models
    max_budget   NUMERIC(18, 6),                -- USD; NULL = unlimited
    spend        NUMERIC(18, 8) NOT NULL DEFAULT 0,
    expires_at   TIMESTAMP,
    blocked      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE spend_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash        VARCHAR(64) NOT NULL,
    model_group       VARCHAR(255),
    model             VARCHAR(255),
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    cost_usd          NUMERIC(18, 8),
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_spend_logs_token ON spend_logs (token_hash, created_at);
